title: BP0323892 | Data Science Portfolio
logo: images/istockphoto-1389238948-612x612.jpg
description: 1st Year Data Science Student at BPP. Passionate about Python, Statistics, and Data Visualization.
show_downloads: true
theme: jekyll-theme-minimal
